[pytest]
testpaths = tests
pythonpath = .
addopts = -v --tb=short --cov=app --cov-report=term-missing --cov-report=html

; pytest tests/api
; pytest tests/unit
; pytest --cov=app --cov-report=term-missing